### ISSUE TITLE
本地直接打开index.js会报错！

### ISSUE THREAD

**Issue by ChanJuanMei** [myst729/Waterfall#4]
找到原因了，不好意思

你好厉害哦

**Comment by myst729** [comment]
老早以前写的烂代码了 😯

**Comment by myst729** [comment]
@ChanJuanMei https://github.com/ChanJuanMei/webfront 这是看起来像是毕业设计之类的项目，你现在是学生吗？

**Comment by ChanJuanMei** [comment]
@myst729 很惭愧已经不是学生了，只是一直做的都是偏向管理系统的项目，反而这种效果做的少。。
